  1 # Theme slightlu ported from Novel theme.
  2 
  3 background            #e3e1d3
  4 foreground            #3b2322
  5 cursor                #73635a
  6 selection_background  #a4a390
  7 color0                #000000
  8 color8                #7f7f7f
  9 color1                #cc0000
 10 color9                #cc0000
 11 color2                #947147
 12 color10               #eaeaea
 13 color3                #d06b00
 14 color11               #d06b00
 15 color4                #7a144a
 16 color12               #0000cc
 17 color5                #cc00cc
 18 color13               #cc00cc
 19 color6                #0087cc
 20 color14               #0086cb
 21 color7                #cccccc
 22 color15               #ffffff
 23 selection_foreground  #dfdbc3
